### ISSUE TITLE
[IBM Power Up] Matrix-Model Simulations using Quantum Computing

### ISSUE THREAD

**Issue by anonymousr007** [XanaduAI/QHack2022#10]
### Team Name: 

**anonymousr007**

### Project Description: 

This project aims to use a truncated (regularized) Hamiltonian for the matrix quantum mechanics models. This Hamiltonian is constructed by considering a truncated Hilbert space in the Fock basis. The truncated Hilbert space is constructed starting from the individual matrix degrees of freedom.

Two types of matrix quantum mechanics models are used

- A Yang-Mills-type bosonic 2-matrix model with SU(2) gauge group, which has 6 bosonic degrees of freedom in total.
- A Supersymmetric 2-matrix model with SU(2) gauge group which corresponds to with the minimal number of degrees of freedom 6 bosons and 3 fermions.

Quantum mechanics with matrix degrees of freedom plays an important role in gauge-gravity duality. Gauge-gravity duality translates difficult problems in quantum gravity to well-defined problems in non-gravitational quantum theories. Although it originated from string–M-theory, connections to various other fields, including 

- Quantum Information Theory
- Condensed Matter Theory
- Cosmology
- Holographic simulation of Quantum Black Holes
- Complex high-dimensional supergravity theories

We use the **Variational Quantum EigenSolver (VQE)** to estimate the low-energy spectrum As for the VQE, the specific architecture that we use does not show a satisfactory performance at strong coupling, perhaps due to the variational forms parametrized by the quantum circuits not adequately probing the full gauge-invariant Hilbert space. This result shows that going beyond the VQE and using more complicated or fully quantum algorithms is not the correct way to approach matrix quantum mechanics for now, because they would require even deeper quantum circuits that are more prone to noise on actual quantum hardware.

### Source code: 

[QHack 2022 Open Hackathon Project](https://github.com/anonymousr007/QHack-2022-Open-Hackathon-Project)

### Resource Estimate: 

- Higher AR memory and joint data prediction across countries/states require more qubits.
- 16-qubit QPU would be a good size for Matrix Model Simulation 

### Challenges:

- [Simulation Challenge](https://github.com/XanaduAI/QHack/blob/master/Open_Hackathon.md#simulation-challenge)
- [Young Scientist Challenge](https://github.com/XanaduAI/QHack/blob/master/Open_Hackathon.md#young-scientist-challenge)
- [IBM Qiskit Challenge](https://github.com/XanaduAI/QHack/blob/master/Open_Hackathon.md#ibm-qiskit-challenge)
- [Quantum Chemistry Challenge](https://github.com/XanaduAI/QHack/blob/master/Open_Hackathon.md#quantum-chemistry-challenge)
- [Science Challenge](https://github.com/XanaduAI/QHack/blob/master/Open_Hackathon.md#science-challenge)

**Comment by co9olguy** [comment]
Thanks @anonymousr007!

The deadline for this Power Up isn't until end-of-day Tuesday (Eastern Time), so feel free to update your project/submission (e.g., by adding a link to your draft code) before then :slightly_smiling_face:

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
