### ISSUE TITLE
[IBM Power Up]Graph Cut Segmentation via QAOA implemented with Qiskit

### ISSUE THREAD

**Issue by JoseIgnacioE** [XanaduAI/QHack2022#11]
# QHack 2022

### Team
Hey there! I am José Ignacio Espinoza Camacho, a Master's student doing my research in quantum computing. I am taking part of the Coding Challenge under the team name **JIEC**.

### Description
Clustering is a set of mathematical and computational methods that are part of the unclassified learning techniques in Machine Learning.  Clustering is frequently used to generate initial information from data sets about which little is known [1].  There are several families of algorithms. This work focuses on Spectral Clustering, specifically in **Normalized Cuts** [2]. In  2000,  J.  Shi  and  J.  Malik  designed  the _Normalized Cuts algorithm_  for  image  segmentation  based on  previous spectral  clustering  works. This algorithm holds an  important  characteristic: we can retrieve different segments of an image by using not only the second eigenvector (like usual spectral clustering algorithms),  but a small set of eigenvectors.

This work lies amidst quantum machine learning and quantum image processing. Quantum Machine Learning (QML) is one of the fastest growing areas in quantum computing.  In contrast with classical machine learning, QML finds atypical patterns more efficiently [3]. Quantum Image Processing is a relatively new area in quantum computing. This field focuses on storing, processing, and retrieving visual information (i.e.  images and video) using quantum  systems  [4]. Based on the work of L. Tse, et al. [5], I pretend to explain and implement the QAOA algorithm they propose using Qiskit.

### External Links
Here you will find the link to the work made by L. Tse, et al [5]. 

- [https://arxiv.org/abs/1812.03050](https://arxiv.org/abs/1812.03050)

In this link you will find an explanatory jupyter notebook of my project _Graph Cut Segmentation via QAOQ implemented with Qiskit_ 

- [https://colab.research.google.com/drive/13blIGHwYVCr4Oh7jf3d69XCRwXbtGWO9?usp=sharing](https://colab.research.google.com/drive/13blIGHwYVCr4Oh7jf3d69XCRwXbtGWO9?usp=sharing)

Finally, in the following link you will find the final source code of my project

- [https://colab.research.google.com/drive/1Ui-NDEs02IQHRm6mFcBcuZNivm5hGAy5?usp=sharing](https://colab.research.google.com/drive/1Ui-NDEs02IQHRm6mFcBcuZNivm5hGAy5?usp=sharing)

### Open Hackathon Challenges
Given the nature of the work [5], the Challenges I would like to apply are:

1. **Access to 16-qubit IBM Quantum machine**. The Dataset uses images of 4x4 pixels, each pixel is represented by 1 qubit. Hence, the algorithm would fit perfectly in the 16-qubit IBM Quantum machine. 

2. **IBM Qiskit Challenge**, Sponsored by [IBM Quantum](https://www.ibm.com/quantum-computing/) and [Université de Sherbrooke](https://www.usherbrooke.ca/iq/)

3. **Hybrid Algorithms Challenge**, Sponsored by [AQT](https://www.aqt.eu/). QAOA algorithms are Variational Algorithms, hence, they are also hybrid - quantum algorithms.

4. **QAOA Challenge**, sponsored by [Entropica](https://www.entropicalabs.com/) 

### References
[1] A. K. Jain,  M. N. Murty,  and P. J. Flynn.  Data clustering:  A review. _ACM Comput. Surv._, 31(3):264–323, September 1999.

[2] Jianbo Shi and J. Malik. Normalized cuts and image segmentation. _IEEE Transactions on Pattern Analysis and Machine Intelligence_, 22(8):888–905, 2000.

[3] Jacob  Biamonte,  Peter  Wittek,  Nicola  Pancotti,  Patrick  Rebentrost,  NathanWiebe, and Seth Lloyd. Quantum machine learning.Nature, 549(7671):195–202,Sep 2017.

[4] Fei Yan and Salvador E. Venegas-Andraca.Quantum Image Processing. SpringerNature Singapore Pte Ltd., 2020.

[5] Lisa Tse, Peter Mountney, Paul Klein, and Simone Severini. Graph cut segmen-tation  methods  revisited  with  a  quantum  algorithm.CoRR,  https://arxiv.org/abs/1812.03050.

**Comment by isaacdevlugt** [comment]
Hey @JoseIgnacioE !

The deadline for this Power Up isn't until end-of-day Tuesday (Eastern Time), so feel free to update your project/submission before then 🙂

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
