### ISSUE TITLE
Quantum Computational Human Neural Network

### ISSUE THREAD

**Issue by hrahman12** [XanaduAI/QHack2022#12]
### Team Name: 
BladeRunner

### Project Description: 

*A brief description of your project (1-2 paragraphs).*
We are deciding to do a Quantum Computational Human Neural Network that mimics the human brain as given from BCI data. We will be using GAN's, QNN's, Autoencoders and LSTM's. We know that even in the biology field we still don't know everything about the human brain, but the synapses and connectivity of the parts such as the frontal, temporal, occipital and parietal lobes are key to basic functionality of life. We will be using Quantum Optical Neural Networks to achieve this, in this way we can use both pennylane and strawberry fields. 

### Source code: 

*A hyperlink to the draft source code for your team's hackathon project (e.g., a GitHub repo).*
https://github.com/hrahman12/QHack-2022-Open-Project-

### Resource Estimate: 

*A 1-2 paragraph written Resource Estimate, indicating how you expect to use the IBM 16-qubit QPU, if awarded, to finish your Open Hackathon project.*
We will use it to benchmark cases for the Neural Network against other devices(both IBM and Amazon).

**Comment by isaacdevlugt** [comment]
Hey @hrahman12 !

The deadline for this Power Up isn't until end-of-day Tuesday (Eastern Time), so feel free to update your project/submission before then 🙂

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
