### ISSUE TITLE
[IBM Power Up] Error mitigation using noise-estimation circuit

### ISSUE THREAD

**Issue by Dran-Z** [XanaduAI/QHack2022#13]
### Team Name: 

CloudKite

### Project Description: 

In current NISQ devices, circuit noise hinders us from obtaining a satisfying outcome. Even for those quantum algorithms specifically designed for NISQ devices like variational quantum algorithms, noise could induce barren plateaus and affect the optimization performance[1]. 

A recent article proposed the idea for error mitigation using a noise-estimation circuit[2]: Before running the working circuit, an estimation circuit based on the working circuit will be executed and used to measure the noise scale. The author has shown that this idea could improve performance when simulating the Heisenberg model, and the improvement is even larger when circuit depth becomes larger. We are going to replicate the result using real noisy backends and apply the idea to more use cases like variational algorithms and QAOA. 

[[1]](https://www.nature.com/articles/s41467-021-27045-6) Wang, S., Fontana, E., Cerezo, M. et al. Noise-induced barren plateaus in variational quantum algorithms. Nat Commun 12, 6961 (2021).
[[2]](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.127.270502) Urbanek, Miroslav, et al. "Mitigating depolarizing noise on quantum computers with noise-estimation circuits." Physical Review Letters 127.27 (2021): 270502.

### Source code: 

[Here](https://github.com/Dran-Z/QHack2022-OpenHackerthon)

### Resource Estimate: 

The 16-qubit QPU could provide the chance to explore the idea's gain for quantum circuits with a large size, which allows us to verify the dominant range in terms of system(qubit) size for this error mitigation protocol. After we implemented the six-qubit example shown in ref [2], we will increase the system size step by step to a 16-qubit example. The number of total shots could be estimated by 16(steps)*3(one without error mitigation, two with error mitigation)*8192(shots) for each simulation.

The access of the 16-qubit device could also give the possibility for us to try more use cases. In general, variational algorithms with noise-estimation circuits would need twice the amount of original shots. In the optimization process, we estimate ~200 iteration to achieve significant performance improvement.

**Comment by isaacdevlugt** [comment]
Hey @Dran-Z !

The deadline for this Power Up isn't until end-of-day Tuesday (Eastern Time), so feel free to update your project/submission (e.g., by adding a link to your draft code) before then 🙂

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
