### ISSUE TITLE
QAOA on KnapSack Variant with optimized mixers

### ISSUE THREAD

**Issue by alekospagon** [XanaduAI/QHack2022#14]
Team - alekospagon

The project is qualified for the 3 categories:
1) QAOA Challenge
2) Hybrid Algorithms Challenge
3) IBM Qiskit Challenge

Project Description:

Abstract: The Project is an application of the QAOA algorithm on a KnapSack variant. Specifically, it is for a problem reducable to KnapSack for which we implemented a quantum circuit (with many optimizations). The problem was introduced to our team on IBM's Fall Challenge 2021. We took this problem further by implementing new mixers for faster convergence proposed in [Quantum Optimization Heuristics with an Application to Knapsack Problems](https://arxiv.org/abs/2108.08805) 

Technical details: We transcribe the problem to the QAOA's C operator. We construct the circuit corresponding to it; then we propose 3 optimizations that reduce the circuit's depth and then we propose an optimization (new mixers) that improves the algorithm's convergence speed. After that, we define a metric for the circuit's accuracy and we measure it for different inputs and repetitions. Last, but not least, using our metric we demonstrate the clear advantage of the new mixers. We propose further optimizations.

We uploaded the Project Pdf, and one power point to present our work. The pdf contains all the details and the source code for the Qiskit Simulation.

[QHACK___QAOA_KnapSack_Variants_with_Optimized_Mixers.pdf](https://github.com/XanaduAI/QHack/files/8117397/QHACK___QAOA_KnapSack_Variants_with_Optimized_Mixers.pdf)
[QHACK___QAOA_KnapSack_Variants_with_Optimized_Mixers___Power_Point___Non_Technincal.pdf](https://github.com/XanaduAI/QHack/files/8117398/QHACK___QAOA_KnapSack_Variants_with_Optimized_Mixers___Power_Point___Non_Technincal.pdf)

**Comment by isaacdevlugt** [comment]
Hey @alekospagon !

The deadline for Power Ups isn't until Wednesday, and final submissions isn't until Friday, so feel free to update your project/submission as you like before these deadlines

**Comment by isaacdevlugt** [comment]
Please make sure to specify which power up you are applying for by labelling this issue. If you want to apply for both, please make a separate submission with the appropriate tag.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
