### ISSUE TITLE
[IBM Power Up] Optimising Molecular Geometries using VQE 

### ISSUE THREAD

**Issue by cheechonghian** [XanaduAI/QHack2022#15]
### Team Name: 

Qanything

### Project Description: 

 The optimisation of molecular geometry is one of many fundamental problems in quantum chemistry. The motivation of this problem stem from the experimental observation that an optimal molecular geometry, which are found via numerical calculations, often correspond to actual molecular structure found in Nature. There is motivation in studying optimal geometry of molecules as sometimes, the unique properties of the substance are attributed to its special molecular structure. For example, the V shaped structure of water explains ice formation and open structure of ice crystals with lower density than liquid water.

In this project, we shall investigate performance of Problem-Inspired Ansatze in solving the optimisation problem of molecular geometry, which are built using Given rotations [[1]](http://arxiv.org/abs/2106.13839)  as simple building blocks. Given rotations are particle-preserving variational circuits for which are useful for approximating molecular ground states. In particular, problem-inspired ansatze will be constructed based on the Exact Decomposition of Unitary Coupled Cluster Single and Double (UCCSD) Unitary [[2]](http://arxiv.org/abs/1910.10130) which are known to be notoriously difficult to implement in practice with the current quantum devices due to its need for deep circuits. Importantly, we plan to employ creative optimization strategies on the both simulated and real hardware for simple molecules, such as H2 and others up to LiH . We also wish to study how the noise can affect the final accuracy on the molecular geometry.

### Source code: 

[Qanything_Chem_Project](https://github.com/cheechonghian/Qanything_Chem_Project)

### Resource Estimate: 
The smallest test case, Hydrogen (H2) molecule will require a quantum circuit at least 4 qubits with 15 independent pauli strings observables.
The largest test case, Lithium Hydride (LiH) molecule will require at least 12 qubits with 631 independent pauli strings observables.

### Challenge Attempting
- Quantum Chemistry Challenge
- Simulation Challenge
- Hybrid Algorithms Challenge 
- IBM Qiskit Challenge

### References:

[[1]](http://arxiv.org/abs/2106.13839) Arrazola, J. M., Matteo, O. D., Quesada, N., Jahangiri, S., Delgado, A., & Killoran, N. (2021). Universal quantum circuits for quantum chemistry.

[[2]](http://arxiv.org/abs/1910.10130) Evangelista, F. A., Chan, G. K.-L., & Scuseria, G. E. (2019). Exact parameterization of fermionic wave functions via unitary coupled cluster theory. The Journal of Chemical Physics, 151(24), 244112.

**Comment by isaacdevlugt** [comment]
Hey @cheechonghian ! 

The deadline for this Power Up isn't until end-of-day today (Eastern Time), so feel free to update your project/submission before then 🙂

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
