### ISSUE TITLE
[IBM Power Up] QAOA for Travelling Salesman Problem Optimization using Qiskit

### ISSUE THREAD

**Issue by AditiRupade** [XanaduAI/QHack2022#16]
### Team Name: 

*QuantumArtist*

### Project Description: 

*Travelling Salesman Problem (TSP) is a known NP-complete problem especially to computer scientists and mathematicians. The problem states that "There is a salesman who is travelling from one city to another to sell something. The goal is to find the shortest path between the cities so that the salesman will be able travel all the cities and return back in as much least time as possible".
Given the statement above, this project will aim to reduce the travel time of the salesman using an Quantum Approximate Optimization Algorithm (QAOA).*

### Source code: 

*A hyperlink to the draft source code for your team's hackathon project (e.g., a GitHub repo).*

### Resource Estimate: 

*Given access to IBM 16-qubit QPU, I would use it to run the algorithm on deeper graphs to understand and eventually try to get higher optimization in the circuit and estimation values*

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
