### ISSUE TITLE
[IBM Power Up] Inside the Quantum Tardis:  Simulating a 1D infinite chain ν = ⅓ FQH state on a finite NISQ device

### ISSUE THREAD

**Issue by oarzi** [XanaduAI/QHack2022#17]
### Team Name: 

Marpeq

### Project Description: 

Our project aims to implement the recent suggestion by Rahmani et al. to simulate the Laughlin wavefunction of the ⅓ FQH state. This suggestion takes advantage of a clever reduction of the 2D state to a 1D system. We plan to implement and execute a circuit, verify it yields the required quantum state, and measure interesting physical properties such as the mutual statistics of quasi-particles. Since current NISQ devices are small and scarcely available, we also intend to implement a pennylane version of the parallelization system proposed by Barrat. The system allows simulations of large systems using only a handful of qubits. Since the FQH state is topologically ordered, we cannot rely on measurements of a local order parameter to verify the circuit generates the intended state. Thus it necessitates the measurement of non-local string operators. This means we must extend Barrat’s algorithm to facilitate measurements of non-local operators. We believe this is possible because the FQH ground state assumes the form of a matrix product state.

One challenging issue we need to face in order to complete our plan is the mitigation of noise. Beyond the inherent noise that inflicts each qubit during each gate application Rahmani et al.’s suggestion assumes a snake-like connectivity topology of the qubits in order to use nearest-neighbor two-qubits. Since the device does not provide such connectivity, the noise is amplified by the requirement to execute additional SWAP gates. These allow the device to provide the connectivity between far away qubits. To overcome this issue, we will use simulator measurements of Rahmani et al.’s idealized circuit as training data for a variational circuit. The parameters of the variational circuit will be optimized to yield the FQH state.

- Creating and Manipulating a Laughlin-Type ν = 1/3 Fractional Quantum Hall State on a Quantum Computer with Linear Depth Circuits. Rahmani, A. PRX Quantum 1, 2020.
-Parallel quantum simulation of large systems on small NISQ computers. Barratt, F. npj Quantum Information (2021).

### Source code: 
Here is a [link](https://github.com/ShapeshiftingMasterOfDarkness/QHack2022-FQHE) to our project’s GitHub repository, we note the work has only just begun:
https://github.com/ShapeshiftingMasterOfDarkness/QHack2022-FQHE
### Resource Estimate: 

*A 1-2 paragraph written Resource Estimate, indicating how you expect to use the IBM 16-qubit QPU, if awarded, to finish your Open Hackathon project.*
The circuit we will implement acts on 3-qubit blocks. Currently, we have access to IBM’s 7 qubit device, which allows maintaining the state of 2 qubit blocks concurrently. However, Rahmani et al. estimate 22 qubits as the desired number for suppression of boundary effects. Using the 16-qubit device will allow us to simulate more extensive systems, closer to that limit. Together with our parallelization scheme, we could accelerate the simulation and obtain more accurate and reliable measurements of more exciting and complicated physical processes. 

For a system of N qubits simulated over d actual qubits, we will need to run O(N/d) measurement cycles. Since the circuit size is linear in the number d of qubits we expect the execution to be fast. So O(dN/d)=O(N) cycles in total are needed, thus we expect our use of the 16-qubit device to be efficient. 

We note that Barratt et al. provided a qiskit implementation of their system. Therefore using it over the 16 qubit IBM device will save us a considerable amount of time.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
