### ISSUE TITLE
[IBM Power Up] Protein Folding Prediction

### ISSUE THREAD

**Issue by Qubit1718** [XanaduAI/QHack2022#20]
### Project Description: 

How do proteins fold? One of the million-dollar questions that we haven’t known the answer for. Understanding why a particular protein only folds that way and why not the other hundreds of thousands of possibilities can take homo sapiens a long way. To invent new drugs and medicines, we need the protein’s structure and that is not that simple and easy. A moderate amino acid chain protein itself can have a conformation size of the mass of the Earth. With the increase in the amino acids in the chain, the potential conformations grow exponentially which is why this problem is hard to tackle using a classical computer.

Alzheimer's disease is a dreadful disease caused in humans where it destroys memory and other important mental functions. In India, over 1 million people suffer from Alzheimer’s disease every year. The main objective of this project is to use quantum computing and find the ground state of the BACE1 exosite binding peptide because almost all of these peptides fold into their ground states. We would love to use different techniques such as Error Mitigation to compare and check the results.

### Source code: 

https://github.com/Qubit1718/QHack-2022-Open-Hackathon-Project/blob/main/QHack_2022_Open_Hackathon_Project_.ipynb

### Resource Estimate: 

As far as this project is concerned, we have only taken the main chain with 6 amino acids and we require 6 qubits to run and execute this experiment. We have not included any side chain in this experiment because of the exponential rise in the number of qubits used and the time it takes to run. We would love to take this project further including the side chain which will obviously require access to a higher qubit machine with which we can find the ground state of the higher amino acid peptide and its conformation.

### Challenges
Amazon Bracket Challenge 
IBM Qiskit Challenge 
Bio-QML Challenge 
Quantum Chemistry Challenge

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
