### ISSUE TITLE
[IBM Power Up] Quantum sea - Classifying water molecules and sodium ions in protein structures

### ISSUE THREAD

**Issue by shadow1229** [XanaduAI/QHack2022#21]
### Team Name: 

Lindwurm 

### Project Description: 

Quantum sea - Classifying water molecules and sodium ions in protein structures   

The goal of the project is building quantum machine learning-based classifiers which can classifies water molecules and sodium ions present in the crystallographic structure of protein obtained by X-ray crystallography, as a kind of toy program for predicting physicochemical properties related with the protein. X-ray crystallography is mainly used to obtain the structure of a protein with high resolution, by using diffraction of X-ray due to electrons in the protein. Due to the nature of the method, small molecules, atoms or ions with the same number of electrons are likely to produce similar peaks. For example, water molecule, one of the small molecules abaundant in protein crystal structures, have 10 electrons, is likely to be confused with sodium ions which has 10 electrons. However, since water molecules does not have net charge, while sodium ions having positive net charge, the structure of proteins that can hold water molecules and sodium ions are likely to be different. From this, water molecules and sodium ions in X-ray crystallography can be distinguished.

In this project, convolutional natural network-based water-sodium ion classifier with input as a voxelized 3D image of the structure of carbon, nitrogen, and oxygen atoms from proteins or other compounds (exclude water) in a cube which center is located at a location where sodium ion or water molecule exists and size of 16Å and grid spacing of 0.5Å. In the last layer before fully connected layer of the classifier, trainable quanvolution neural network was used for
 convolution and pooling of 2x2x2 grid a into 1x1x1 grid. With the help of IBM's 16-qubit quantum computer, the performance between 2x2x2 quanvolutional layer implemented as 2 circuits of 4-qubit quanvolution circuit and one circuit of 8-qubit quanvolution can be compared. Furthermore, 16-qubit circuit quanvolutional neural network as composed layer consists with convolution of dilated convolution and non-dilated convolution can be tested. 

### Source code: 

https://github.com/shadow1229/Qhack_2022/tree/main/Quantum_sea

### Resource Estimate: 

Training will be done by quantum simulator, and IBM's Quantum Computer is expected to be used in the comparing the performance between classifiers. From the currently implemented method, it is expected that a 4-qubit circuit with four random rotations and two layers will be used 13,824,000 shots. (108 input structures * 64 channels * 2 circuits * 1000 shots per exposure value) In similar mannner, evaluation of 8-qubit circuit and 16-qubit circuit are expected to use 6,912,000 shots each.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
