### ISSUE TITLE
Quantum Computing -based Optimization for Sustainable Data Workflows in Cloud Infrastructures

### ISSUE THREAD

**Issue by valterUo** [XanaduAI/QHack2022#22]
### Team Name: 

Qumpula Quantum (I come from the University of Helsinki from _Kumpula_ campus)

### Project Description:

Data centers are consuming a huge amount of energy and producing an unbearable carbon footprint. This work proposes a data workflow optimization algorithm that divides the data workload among multiple data centers so that the computations can be performed as sustainably as possible. 

Google has developed a carbon footprint metric that enables users to track their computations emissions. Inspired by the idea that in the future such detailed data would be available, the project proposes a solution how to divide the computations along with data centers (or even machines in the centers) so that the carbon footprint is minimized. The problem is formulated as a quadratic unconstrained binary optimization problem. 

Since hackathons are also learning experiences, I planned to implement the algorithm using multiple different quantum hardware and software. This will include a D-wave's quantum annealers running in Amazon Braket and NISQ devices in Amazon Braket and in IBM Quantum systems.

See the full project description with references in [this document](https://github.com/valterUo/Quantum-Computing-based-Optimization-for-Sustainable-Data-Workflows-in-Cloud/blob/main/Quantum_Computing__based_Optimization_for_Sustainable_Data_Workflows_in_Cloud.pdf) which is along with the Github repo. I also planned to finalize the project as a demonstration system for a suitable database conference.

### Source code: 

Source code, which is under work, is in Github repo [Quantum Computing -based Optimization for Sustainable Data Workflows in Cloud Infrastructures](https://github.com/valterUo/Quantum-Computing-based-Optimization-for-Sustainable-Data-Workflows-in-Cloud/blob/main/main.ipynb).

### Resource Estimate: 

I planned to scale the problem so that I would be able to demonstrate it on a 16-qubit machine.

![photo_2022-02-21_15-28-46](https://user-images.githubusercontent.com/33791450/155206441-ba1bd334-8dc4-4a44-950e-6300293b5e7f.jpg)

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
