### ISSUE TITLE
Plant Disease Detection System using QCNNs

### ISSUE THREAD

**Issue by bopardikarsoham** [XanaduAI/QHack2022#23]
### Team Name: 
QRiders

### Project Description: 
Solanaceous crops(Potato, Tomato, and Pepper) are one of the most cultivated and in-demand crops after rice and wheat. Solanaceous farming dominates as an occupation in the agriculture domain in more than 125 countries. However, even these crops are, subjected to infections and diseases, mostly categorized into two grades: 
1) Early blight(caused by fungus) 
2) Late blight(caused by specific micro-organisms) 

Farmers who grow these crops suffer from serious financial standpoint losses each year. Wouldn't it be amazing if the farmer could discover this ailment early and treat it properly? This can prevent a lot of waste and financial loss.

### Source code: 
https://github.com/bopardikarsoham/QHack-Open-Hackathon

### Resource Estimate: 

If I get access to the 16 qubit IBM machine, I'll be able to encode somewhat larger images than a standard 2x2 or 4x4. It has the potential to significantly improve my project and understanding of QML algorithms on larger qubit devices.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
