### ISSUE TITLE
[IBM Power Up] Quantum Monte Carlo for Pricing Financial Derivatives

### ISSUE THREAD

**Issue by ShreyBiswas** [XanaduAI/QHack2022#25]
# Team Quest: <br>Quantum Monte Carlo for Pricing Financial Derivatives

Estimating how to price Financial Derivatives - like options such as puts and calls - is a difficult task due to the huge number of possible changes in variables. While estimation techniques such as Classical Monte Carlo exist, they can easily rack up large 'error' or uncertainty; getting rid of this is time-consuming and costly.

In the case of the Classical Monte Carlo, for example, error scales with 1/sqrt(M) where M is the number of simulations. Because of this, in order to halve the error, you must quadruple the simulation number. To reduce the error to useful amounts, the quadratic scaling can mean large numbers of simulations are needed.
In Quantum Monte Carlo, however, we can offer a Quadratic Speedup, so error scales with 1/M. This has huge potential, since it can greatly improve the accuracy of Option Pricing while reducing the intensity of simulation required for them. 

Team Quest hopes to explore this by implementing work in [Quantum computational finance: Monte Carlo pricing of financial derivatives](https://arxiv.org/abs/1805.00109), seeing how Quantum Monte Carlo can be realised and executed.
<h1></h1>

[**Github Repository**](https://github.com/StreakSharn/Quest)
<hr>

## Challenges:
- IBM Challenge
- Quantum Finance Challenge
- [Google Quantum AI Challenge](https://storage.googleapis.com/pub-tools-public-publication-data/pdf/117b7980445cb3235c2032c83a00678a8f00303a.pdf)
- Quantum Entrepreneur Challenge
- Young Scientist Challenge

**Members: @StreakSharn, @DSamuel1, @r-agni**

**Comment by isaacdevlugt** [comment]
Please make sure to specify which power up you are applying for by labelling this issue. If you want to apply for both, please make a separate submission with the appropriate tag.

**Comment by ShreyBiswas** [comment]
Redone submission for powerup with correct tags. Thanks for the heads-up!
