### ISSUE TITLE
[IBM Power Up] Testing noise-induced robustness in quantum classifiers

### ISSUE THREAD

**Issue by armandoangrisani** [XanaduAI/QHack2022#27]
### Team Name: 

*Jourdan*

### Project Description: 

**Testing noise-induced robustness in quantum classifiers**

*The capabilities of near-term quantum device are severely limited by the presence of experimental perturbation, thus a number of noise-mitigating approaches have been proposed. Yet, a slight amount of noise might be useful in some contexts: it's well-known that the careful addition of noise can ensure desirable properties such as differential privacy and robustness to adversarial examples [1,2,3].*

*Prior research in this direction investigated the properties of depolarizing noise, both theoretically and through numerical simulations [4]. In our project, we train a variational quantum classifier on the "California housing" dataset [5] and we test its robustness to adversarial examples crafted with the ART library [6]. 
We perform our experiments both on classical simulators (Pennylane, Qiskit) and on NISQ architectures (IBM, IonQ, Rigetti). Thus, we study for the first time the robustness properties ensured by realistic noise models.*

**References**

[1] M. Lecuyer et al., Certified Robustness to Adversarial Examples with Differential Privacy, https://arxiv.org/abs/1802.03471
[2] L. Zhou and M. Ying, Differential Privacy in Quantum Computation, https://ieeexplore.ieee.org/document/8049724
[3] A. Angrisani, M. Doosti and Elham Kashefi, Differential Privacy Amplification in Quantum and Quantum-inspired algorithms, under review
[4] Y. Du et al., Quantum noise protects quantum classifiers against adversaries, https://arxiv.org/abs/2003.09416
[5] https://inria.github.io/scikit-learn-mooc/python_scripts/datasets_california_housing.html
[6] https://adversarial-robustness-toolbox.readthedocs.io/en/latest/#

### Source code: 

*https://github.com/Matx00/qhack-jourdan/blob/main/qhack.ipynb*

### Resource Estimate: 

*Whereas prior work investigated differential privacy and robustness in quantum classifiers either theoretically or numerically, we conduct experiments on NISQ devices.  Exploring the properties of the quantum noise that inherently affects the 16-qubit IBM machine would be extremely relevant for many use-cases.*

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
