### ISSUE TITLE
[IBM Power Up] Quantum Monte Carlo for Pricing Financial Derivatives

### ISSUE THREAD

**Issue by ShreyBiswas** [XanaduAI/QHack2022#30]
#### Team Quest
Members: @StreakSharn, @DSamuel1, @r-agni.

### Project Description: 

Estimating how to price Financial Derivatives - like options such as puts and calls - is a difficult task due to the huge number of possible changes in variables. While estimation techniques such as Classical Monte Carlo exist, they can easily rack up large 'error' or uncertainty; getting rid of this is time-consuming and costly.

In the case of the Classical Monte Carlo, for example, error scales with 1/sqrt(M) where M is the number of simulations. Because of this, in order to halve the error, you must quadruple the simulation number. To reduce the error to useful amounts, the quadratic scaling can mean large numbers of simulations are needed.
In Quantum Monte Carlo, however, we can offer a Quadratic Speedup, so error scales with 1/M. This has huge potential, since it can greatly improve the accuracy of Option Pricing while reducing the intensity of simulation required for them. 

Team Quest hopes to explore this by implementing work in [Quantum computational finance: Monte Carlo pricing of financial derivatives](https://arxiv.org/abs/1805.00109), seeing how Quantum Monte Carlo can be realised and executed.

### Source code: 

[**Github Repository**](https://github.com/StreakSharn/Quest)

### Resource Estimate: 

At small scales with few qubits, the Quantum Monte Carlo offers no tangible speed-up or improvement in error over its Classical counterpart - in fact, due to the inherent errors present within NISQ systems, even with error correction it often comes out worse. However, at larger scales, the advantage gained from Quantum methods can lead it to outstrip the Classical equivalent.

**IBM's 16-qubit QPU would allow us to approach these scales, and more effectively demonstrate advantages offered by Quantum Monte Carlo algorithms.** 
This could allow us to expand the breadth of our Project, and examine/evaluate the comparison between Quantum and Classical methods.

<hr>

## Challenges:
- IBM Challenge
- Quantum Finance Challenge
- [Google Quantum AI Challenge](https://storage.googleapis.com/pub-tools-public-publication-data/pdf/117b7980445cb3235c2032c83a00678a8f00303a.pdf)
- Quantum Entrepreneur Challenge
- Young Scientist Challenge

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
