### ISSUE TITLE
[IBM Power Up] Calculating Molecular Vibronic Spectra

### ISSUE THREAD

**Issue by alexdzm** [XanaduAI/QHack2022#31]
### Project Description: 
To implement an algorithm for determining the vibrionic structure of multi-atomic molecules using quantum phase estimation on IBM hardware. This problem is important in understating the optical interaction with molecules and is a good example of a classically intractable problem. As described by the authors of  [this](https://arxiv.org/pdf/1812.10495.pdf)paper, accurate spectra of larger molecules have not been calculated.

The aim of this project is to implement the zero temperature approach in the paper above, and if there is time to include the modifications suggested in it and in [this](https://arxiv.org/pdf/2009.05066.pdf) follow up paper. Our team has experience in quantum optics and molecular physics as well as a qualified qiskit developer. 

### Source code: 

Code, once public will be at this repo:
https://github.com/alexdzm/Qhack_open

### Resource Estimate: 

If non-zero temperature systems will be considered, an extra register is required for phase estimation. More quits will help with solving this problem. More quits are useful even in the zero temperature case, where a larger register allows us to consider higher vibrational states that increase the accuracy of any simulation.

We want to use a real quantum device because understanding how real noise effects this algorithm will be important in understanding whether it will work on NISQ hardware, or if it will have to wait for more fault tolerant quantum hardware.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
