### ISSUE TITLE
[IBM Power Up] RNA Folding with Quantum Computers

### ISSUE THREAD

**Issue by JuanGiraldo0212** [XanaduAI/QHack2022#32]
### Team Name: 

*qnyble*

### Project Description: 

*RNAs are nucleotide polymers fundamental to a diversity of elementary biological functions, including the (de)coding and regulation of genes, protein construction, cellular signaling, and catalysis [1]. Integral to these roles is the capacity and propensity of RNAs to self-interact through hydrogen-bond base-pairing between nucleotides and fold into specific, stable structures [2]. This folded structure of an RNA along with its primary sequence chemistry combine to dictate its interactions with other biomolecules [3]. Understanding and predicting RNA folding is thus a pressing interest of the biological sciences, basic and applied [4, 5].*

*RNA folding prediction from primary sequence information alone remains challenging classically, viewed from both the standpoints of chemical dynamics and combinatorial optimization of free energy. Quantum approaches, with their demonstrable advantage in both of these realms, therefore lend themselves well to the RNA folding problem. To our knowledge, only one attempt has been made to map RNA folding to quantum computing, via quantum annealing [6]. With this project, we seek to: (1) modify the Hamiltonian presented therein to better reflect the underlying chemistry of base-pairing, and (2) optimize the free parameters of the Hamiltonian against a suite of RNAs with known structures. Expanding on (2), we aim to implement and test our Hamiltonian with the quantum annealing hardware of D-Wave, and demonstrate a parallel approach with gate-based hardware via QAOA, using the very same Hamiltonian.*

References:

[1] J. Li and C. Liu, “Coding or noncoding, the converging concepts of RNAs,” Frontiers in
Genetics, vol. 10, May 2019.
[2] G.L.ConnandD.E.Draper,“RNAstructure,”Current Opinion in Structural Biology,vol.8,
no. 3, pp. 278–285, Jun. 1998.
[3] S. R. Holbrook, “RNA structure: the long and the short of it,” Current Opinion in Structural
Biology, vol. 15, no. 3, pp. 302–308, Jun. 2005.
[4] M. D. Disney, “Targeting RNA with small molecules to capture opportunities at the intersec-
tion of chemistry, biology, and medicine,” Journal of the American Chemical Society, vol.
141, no. 17, pp. 6776–6790, Mar. 2019.
[5] N. G. Walter and L. E. Maquat, “Introduction—RNA: From single molecules to medicine,”
Chemical Reviews, vol. 118, no. 8, pp. 4117–4119, Apr. 2018.
[6] D. M. Fox, C. M. MacDermaid, A. M. Schreij, M. Zwierzyna, and R. C.
Walker, “RNA folding using quantum computers,” May 2021.

### Source code: 

*https://github.com/JuanGiraldo0212/Qhack-qnyble*

### Resource Estimate: 

*Given that the proposed Hamiltonian for this specific problem works by mapping one qubit to a possible stem from a RNA sequence, we are directly constrained in the size of our inputs by the size of the selected quantum computer. Most RNAs have a large stem count making it impossible to use our methods to predict their secondary structure while only having access to the free-tier IBM machines. This would limit our experiments to small and trivial sequences which won't be able to give us complete feedback on how well our methodology is at solving the general problem.*

*If we were to have access to the IBM 16-qubit QPU we would be able to test over a more complete and expressive dataset of RNA sequences in trialling our solution, allowing us to find limitations and improvement opportunities for this specific approach.*

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
