### ISSUE TITLE
[IBM Power Up] Forex/COVID Forecasting with Variational Quantum AutoRegressive (VQAR)

### ISSUE THREAD

**Issue by toshi-koike-akino** [XanaduAI/QHack2022#33]
### Team Name: 

talll

### Project Description: 

We demonstrate a variational quantum autoregressive model (VQAR) to forecast stochastic data trends of foreign exchange rates and COVID-19 cases. 
[Readme](https://github.com/toshi-koike-akino/vqar/blob/main/README.md)

### Source code: 

Code repository is found at [repo](https://github.com/toshi-koike-akino/vqar)

### Resource Estimate: 

Higher AR memory and joint data prediction across countries/states require more qubits.
16-qubit QPU would be a good size for forex/covid prediction.

### Open Hackathon Challenges/Prizes

Our project is qualified for
- Quantum Finance Challenge
- Amazon Braket Challenge
- IBM Qiskit Challenge 
- Quantum Chemistry Challenge

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
