### ISSUE TITLE
[IBM Power Up] Generalized Sub Space Search VQE for finding Kth excited state energy of a Physical System

### ISSUE THREAD

**Issue by Jay-Patel-257** [XanaduAI/QHack2022#34]
### Team Name: 

Parmanu

### Project Description: 

The goal of the project is to explore the <b><i>Sub Space Search VQE Algorithm</i></b> to calculate the Kth excited-state energy of a given hamiltonian. There are three variants of SSVQE shown below:

* <b>Sub Space Search VQE:</b> The algorithm uses a two-step optimization process to calculate the Kth excited state energy.
* <b>Weighted Sub Space Search VQE to find the energy of Kth excited state:</b> The algorithm uses a one-step optimization process to calculate the Kth excites state energy. 
* <b>Weighted Sub Space Search VQE to find energies up to K excited states:</b> The algorithm calculates all the excited state energies up to the Kth state in a single optimization process. The only drawback is the runtime due to the complexity of the cost function.

This project aim towards comparing the results of all three algorithms and how they perform on noiseless and noisy systems.

### Source code: 

[SSVQE](https://github.com/Jay-Patel-257/Qhack-2022)

### Resource Estimate: 

The current tests have been done using the Hamiltonian of the H2 molecule. which alone requires 4 qubits. We want to try these algorithms for relatively large or complex molecules to obtain an idea about how they perform on noisy channels and possibly try to apply Error Mitigation techniques to balance it out. For that, we would like to have access to the 16-Qubit system.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
