### ISSUE TITLE
QONN to mimic brain

### ISSUE THREAD

**Issue by hrahman12** [XanaduAI/QHack2022#35]
### Team Name: 
BladeRunner

### Project Description: 
We are working on a Quantum Optical Neural Network that mimics the Brain. We are incorporating Speech, Image and Memory data. We want to simulate the human brain, despite our limited knowledge of the human brain we can use GAN’s, CNN’s and Circuit Optimizing to simulate the connections between the speech to image and memory to motor senses. 
We use photons to achieve this high speed of communication between neurons.

### Source code: 

https://github.com/hrushikesh890/Qhack2022_BladeRunner

### Resource Estimate: 
We will be using the AWS credits to run benchmarking tests against the AWS systems.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
