### ISSUE TITLE
[IBM Power Up] Quantum Uno

### ISSUE THREAD

**Issue by fomalhautn** [XanaduAI/QHack2022#39]
### Team Name: 

ARE YA WINNING, SON?
[Anastasiia Andriievska](https://github.com/fomalhautn), [Artem Kuzmichev](https://github.com/artem-phys)

### Project Description: 

You certainly know the classical Uno game! Any card you put down must either be the same color or the same number as the card in the center. 

### Source code: 

https://github.com/artem-phys/quantum-uno

### Resource Estimate: 

It is very important to evaluate how quantum circuits should be built on quantum computers with a large number of qubits. In a long perspective, our team planned to begin a start-up with implications on mitigating errors on quantum hardware. Gamification in this turn serves as an inspirational way to involve everyone to learn prominent quantum technologies. 

### Open Hackathon Challenges

Our project is qualified for:

* IBM Qiskit Challenge
* Google Quantum AI Research Challenge
* Hybrid Algorithms Challenge
* Quantum Entrepreneur Challenge
* Science Challenge
* Young Scientist Challenge

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
