### ISSUE TITLE
[IBM Power Up] QuHE

### ISSUE THREAD

**Issue by FerjaniMY** [XanaduAI/QHack2022#40]
### Team Name: 

AlFerjani ( registered as Qonlyme )

### Project Description: 

Quantum computers will tackle problems in different fields such as medical research and finance, where the protection of sensitive data is a must. But quantum computers on the cloud can be threaten for security, particulary when delegating a potential data to such computers. In this context, clients, with limited computational ability, will want to use the services offered by quantum computation and communication protocols, in a way that their privacy is guarantee.

Homomorphic encryption (HE) enables arbitrary computation on encrypted data without decryption.  Similarly to classical HE, quantum homomorphic encryption (QHE) allows clients with limited computational ability to delegated computations to untrusted quantum servers.

This project, we developed QuHE, a simple library for quantum homomorphic enryption using Qiskit in which we implement some quantum homomorphic encryption protocols to allow a quantum computer to compute on encrypted data. Then, we provide an implementation of quantum search on encrypted data using QuHE.

### Source code: 

https://github.com/FerjaniMY/QuHE

** More description will be given later before the final deadline of the hackathon.

### Resource Estimate: 

We aim to use approximately 10 qubits on the IBM 16-qubit QPU, to test the implementation of quantum search on encrypted data on the real quantum hardware.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
