### ISSUE TITLE
[IBM Power Up] Quantum-Counselor-for-Portfolio-Investment

### ISSUE THREAD

**Issue by MaldoAlberto** [XanaduAI/QHack2022#42]
### Team Name: 

Avocados

### Project Description: 

The Quantum Counselor for portfolio investment is a tool with two main objectives: forecasting the trend of assets price and optimizing portfolio returns, both using quantum computing techniques. For the case of the forecasting method, we use a hybrid method that combines a deep learning model of classical LSTM layers with quantum layers. For the case of portfolio optimization, the quantum algorithms of QAOA and VQE are used to solve the problem and will be compared with CPLEX, a classical solver. Both tools are deeply connected because the forecasted price of the different assets is used for the cost function construction.

### Source code: 
The source code of our project you can find [here](https://github.com/alejomonbar/Quantum-Counselor-for-Portfolio-Investment)

### Resource Estimate: 

We would like to have the IBM Quantum power-up because we want to test our small-size portfolio optimization QAOA model on real quantum devices to test error mitigation techniques. The Small size model consists of 5 stocks and 3 periods of time (this requires 15 qubits).  We want to prove the best combination with different techniques for this project using VQE, QAOA, with various optimizers and do a comparative using the classical method Cplex.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
