### ISSUE TITLE
[AWS Power Up] RNA Folding with Quantum Computers

### ISSUE THREAD

**Issue by JuanGiraldo0212** [XanaduAI/QHack2022#43]
### Team Name: 

*qnyble*

### Project Description: 

*RNAs are nucleotide polymers fundamental to a diversity of elementary biological functions, including the (de)coding and regulation of genes, protein construction, cellular signaling, and catalysis [1]. Integral to these roles is the capacity and propensity of RNAs to self-interact through hydrogen-bond base-pairing between nucleotides and fold into specific, stable structures [2]. This folded structure of an RNA along with its primary sequence chemistry combine to dictate its interactions with other biomolecules [3]. Understanding and predicting RNA folding is thus a pressing interest of the biological sciences, basic and applied [4, 5].*

*RNA folding prediction from primary sequence information alone remains challenging classically, viewed from both the standpoints of chemical dynamics and combinatorial optimization of free energy. Quantum approaches, with their demonstrable advantage in both of these realms, therefore lend themselves well to the RNA folding problem. To our knowledge, only one attempt has been made to map RNA folding to quantum computing, via quantum annealing [6]. With this project, we seek to: (1) modify the Hamiltonian presented therein to better reflect the underlying chemistry of base-pairing, and (2) optimize the free parameters of the Hamiltonian against a suite of RNAs with known structures. Expanding on (2), we aim to implement and test our Hamiltonian with the quantum annealing hardware of D-Wave, and demonstrate a parallel approach with gate-based hardware via QAOA, using the very same Hamiltonian.*

### Source code: 

https://github.com/JuanGiraldo0212/Qhack-qnyble

### Resource Estimate: 

*To train the free parameters of our Hamiltonian to achieve the best possible RNA prediction, and understand more generally the efficacy of our model, we need to test over many structures, both with annealers and gate-based machines. On the annealing side, D-Wave affords public users one hour of QPU access time per month, and in our experience this is limiting to a project which requires many runs for calibration/optimization purposes.*

*If we were granted additional access to the D-Wave QPUs through AWS/Braket, we would be able to test over a more complete set of parameter combinations in trialling our solution, allowing us to better find and report limitations and improvement opportunities for this specific approach. Further, we would have the opportunity to work with the gate-based machines of IonQ and Rigetti in a similar manner (via QAOA as noted in the project description), which would permit us to compare results between machines and methods.*

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
