### ISSUE TITLE
[IBM Power Up] Predicting ground state of molecule with novel quantum descriptor using QML 

### ISSUE THREAD

**Issue by justids** [XanaduAI/QHack2022#46]
### Team Name: 

SexyQuantumGuys

### Project Description: 

Classical Neural Networks (NNs) have been used in various ways to predict the ground state of molecules [1]. In such NN-based schemes, atom-centered symmetry functions (usually referred to as ‘descriptors’) are employed to ensure the translational, rotational, and permutation invariance of the many-body system. Considering the quantum version of this approach, we aim to achieve higher accuracy in predicting the ground state of molecules in shorter time, using Quantum Hybrid Neural Networks based on novel quantum descriptors with learnable Hamiltonian.

Also if possible, we are trying to make a Hamiltonian for the Bond Order Potential(BOP). Bonding potential is the largest part of molecule's energy. So by making a nice bonding Hamiltonian, the energy prediction will be much better. The energy will be predicted with the QAOA Method. 

### Source code: 

*A hyperlink to the draft source code for your team's hackathon project (e.g., a GitHub repo).*

https://github.com/justids/SexyQuantumGuys

*A 1-2 paragraph written Resource Estimate, indicating how you expect to use the IBM 16-qubit QPU, if awarded, to finish your Open Hackathon project.*

To make more accurate prediction, we need to use as many as possible qubits for the descriptors. So we will try up to 12 qubits to  predict it well.

###Challenges
Amazon Braket Challenge
IBM Qiskit Challenge
Hybrid Algorithms Challenge
QAOA Challenge
Quantum Chemistry Challenge
Simulation Challenge
Young Scientist Challenge

###Reference
Jörg Behler
Chemical Reviews 2021 121 (16), 10037-10072
DOI: 10.1021/acs.chemrev.0c00868

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
