### ISSUE TITLE
[IBM Power Up] Learning Based Error Mitigation for VQE

### ISSUE THREAD

**Issue by jyryu98** [XanaduAI/QHack2022#49]
### Team Name: edelweiss
@jeungrac @jyryu98 @Eyuel-E

### Project Description: 
Variational Quantum Eigensolvers (VQE) for calculating ground state energies of molecules are one of the major applications of noisy intermediate scale quantum (NISQ) computers. However for VQE to be viable on NISQ computers, powerful error mitigation protocols are needed due to the high level of noise.  

In this project, we investigate applications of a learning based quantum error mitigation (LBEM) method [[1]](https://doi.org/10.1103/PRXQuantum.2.040330) on VQE for molecular ground state energy calculation. LBEM models an error free result with a quasi probabilistic mixture of noisy results. This distribution is learned via an _ab initio_ process, without prior knowledge on the hardware error model. Clifford circuits are used for the training, so classical simulation is efficient, and the mitigation takes account of both spatial and temporal correlations.

 [[1] Strikis, Armands, et al. "Learning-based quantum error mitigation." PRX Quantum 2.4 (2021): 040330.
](https://doi.org/10.1103/PRXQuantum.2.040330) 
### Source code: 
[Github repository](https://github.com/jyryu98/LBEM_for_VQE) 

### Resource Estimate: 
We would like to use a 16 qubit hardware to investigate the performance of LBEM on molecules beyond H<sub>2</sub>. Some candidate molecules are H<sub>2</sub>O and BeH<sub>2</sub>. LBEM is thought to be scalable to deep circuits on large systems.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
