### ISSUE TITLE
[AWS Power Up] Simulating collective neutrino oscillation using QAOA algorithm

### ISSUE THREAD

**Issue by bachbao** [XanaduAI/QHack2022#50]
### Team Name: 
	QuantumRing

### Project Description: 

Neutrino Oscillation which was first predicted by Bruno Pontecorvo in 1957, has been a great theoretical and experimental interest, as its precise properties can shed light on several properties of the neutrino. The experimental discovery of neutrino oscillation proves that neutrino has non-zero mass, which then causes a required modification to the Standard Model of particle physics. This experimental work by Takaaki Kajita and Arthur B. McDonald was so great that it was recognized with the 2015 Nobel Prize for Physics. Due to the potential of this process, many attempts have been conducted to gain a profound understanding of the phenomenon. In this project, we try to dive in and explore this complex quantum dynamic but with a different approach.  
    
Using a quantum computer, our team try to simulate collective flavor oscillations which are created by the interaction neutrino-neutrino in a neutrino cloud with a high density of neutrinos. This process can happen in supernovae and the early universe - astrophysical scenarios with large neutrino density. In this project, we are considering a two-flavor case of interacting neutrinos which leads us to demonstrate the time and space evolution of the set of amplitudes from a Schrodinger equation:
    
$\ket{\phi(t)} = \exp[-iHt]\ket{\phi_{0}}$
    
The H - Hamiltonian from the equation is the Hamiltonian for neutrino flavor evolution in an environment with a high density of neutrinos which include vacuum and forward-scattering interaction contributions. Here we use QAOA (Quantum Approximate Optimization Algorithm) to realize this Hamiltonian with the ambition to scale the system to as many neutrinos as possible, this is where we need a quantum computer with many qubits to perform our quantum circuit. From this simulation, we aim to find a way to simulate many neutrinos interacting systems with polynomial scale-up which will become a great tool for researchers and scientists to look into this complex neutrino dynamic.

### Source code: 

https://github.com/bachbao/Simulating-collective-neutrino-oscillation-using-QAOA-algorithm

### Resource Estimate: 

In this project, we plan to use the power of a real quantum computer, therefore a great need for resources from a real quantum computer is what we want. By implementing the QAOA to realize the neutrino Hamiltonian, we will need to use quantum tomography which means running multiple circuits with many shots to retrieve the initial state. That's our first reason, we need resources from AWS to gain the ability to run many jobs on the Rigetti and Ionq quantum computers, to be more specific Ionq quantum computing can help us a lot with its fully connected machine as we will use many Toffoli gates across our circuits. The second reason is in this current generation of quantum computers, noisy, near-term, intermediate size, it is important to check whether our method can work well using a real quantum computer as the project will lose most of its application meaning if it is only presented by using the simulator. This comes to our final and most important reason for demanding the resources from AWS power up, we plan to scale up our system to as many neutrinos as possible, therefore we want to have a large-scale quantum computer and the quantum computers from Rigetti and Ionq satisfy our need.

### Reference:
Benjamin Hall, Alessandro Roggero, Alessandro Baroni, Joseph Carlson. "Simulation of Collective Neutrino Oscillations on a Quantum Computer." arXiv preprint arXiv:2102.12556 (2021).

Zewei Xiong. "Many-body effects of collective neutrino oscillations" arXiv preprint arXiv:2111.00437 (2021).

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
