### ISSUE TITLE
[IBM Power Up] Optimizing Quantum Graph Neural Networks for the Particle Tracking Problem

### ISSUE THREAD

**Issue by edenian** [XanaduAI/QHack2022#54]
### Team Name: 

*The Superpositioned States of America*

### Project Description: 

[Full IBM Project Proposal](https://github.com/XanaduAI/QHack/files/8121957/IBM_Project_Proposal.pdf)

Our work focuses on Quantum Graph Neural Networks (QGNNs), to solve the particle tracking reconstruction challenge. Specifically, we are looking to focus on the detailed analysis of the vanishing gradient problem, long training times, and how robust the overall approach is to noise from real quantum computers, which have been mentioned but not addressed yet in prior work. Our work aims to improve the viability of the QGNN method for particle tracking problems.

### Source code: 

[Optimizing Quantum Graph Neural Networks for the Particle Tracking Problem.](https://github.com/amirebrahimi/QHack-2022-Hackathon)

### Resource Estimate: 

Currently, our team has secured initial power-ups in the form of Amazon Braket credits and access to a 7-qubit IBM quantum machine. Original QEN circuit used in the [A Quantum Graph Neural Network Approach to Particle Track Reconstruction](https://arxiv.org/abs/2007.06868) utilizes 7 qubits. However, the QNoN circuit uses 11 qubits, which is why having access to IBM’s 16-qubit machine would be helpful for benchmarking purposes.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
