### ISSUE TITLE
Entanglement-assisted quantum autoencoders (EAQAE)

### ISSUE THREAD

**Issue by baczyk1** [XanaduAI/QHack2022#55]
### Team Name: 

Samras

### Project Description: 

Quantum entanglement used as a resource adds an advantage that cannot be obtained with purely classical approaches. This phenomenon manifests itself in CHSH game and quantum superdense coding, where entanglement boosts the winning probabilities for the players and communication rate, respectively. 

In our project, we investigate the use of entanglement in the task of quantum autoencoding. Quantum autoencoders [1] compress quantum information into smaller dimensional Hilbert spaces, and moreover, it is known that entanglement resources can aid in this compression [2]. We take state-of-the-art quantum autoencoder strategies, and add additional entanglement resources to test for a compression advantage. We aim to test the approach on datasets such that the known autoencoder schemes do not compress and decompress the data properly, but when we add the entanglement resources, the result improves. Indeed part of our project is to identify such datasets - at this point we are working with the breast cancer data set and with the credit card fraud dataset. 

We believe that use-cases beyond current research directions might arise with regards to entanglement-assisted quantum autoencoders. They might play a role in quantum state transmission, where one party physically transmits a quantum state to another party. The two parties, as in superdense coding and the CHSH game, share entanglement ahead of time. The sending party uses her share of entanglement to aid in compressing the total state she wants to transmit and then transmits. The receiver uses his share to decompress the state and potentially de-noise his received quantum states. Such scenarios already arise in multi-processor quantum computing, where quantum states move between various quantum processors, or in schemes like quantum key distribution, where some schemes like E91 and DI-QKD, already deploy quantum entanglement as a resource. 

[1] Romero, Jonathan, Jonathan P. Olson, and Alan Aspuru-Guzik. "Quantum autoencoders for efficient compression of quantum data." Quantum Science and Technology 2.4 (2017): 045001.

[2] Z. B. Khanian and A. Winter, "Entanglement-Assisted Quantum Data Compression," 2019 IEEE International Symposium on Information Theory (ISIT), 2019, pp. 1147-1151, doi: 10.1109/ISIT.2019.8849352.

### Source code: 

https://github.com/VoicuTomut/temporaryRepoQhack

### Resource Estimate: 

We intend to run experiments on QPUs for the validation or falsification of our concept. We will start with 4 qubits encoding MNIST dataset images using either angle (2 by 2 pixelated pictures) or amplitude encoding (4 by 4 pixelated pictures). The amount of entanglement qubits needed to gain an advantage is not yet known, as we are currently working towards preliminary results showing advantage. AWS Braket offers simulation platforms like SV1 which are high-performance and can simulate up to 34 qubits which we believe will provide just enough qubit resources to test our approach (4 data qubits, reference qubits, a qubit for swap test, entanglement resources qubits, additional auxiliary qubits). Later on we would like to work with breast cancer and finance datasets. For each we would need around 1000 backends runs with 2500 each. Our simulation results demonstrate that quantum auto encoders might serve as a great tool for anomaly detection for the above-mentioned cases.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
