### ISSUE TITLE
[IBM Power Up] LiH exicited states

### ISSUE THREAD

**Issue by aoowweenn** [XanaduAI/QHack2022#57]
### Team Name: 
QStruggler

### Project Description: 

We want to find the first excited state of a LiH molecule.
There are two excited states (2-1Sigma+, 1-3Sigma+) very near the ground state.
Reference: https://aip.scitation.org/doi/10.1063/1.1677704
We will try to differentiate these two states.

### Source code: 

[GitHub repo](https://github.com/aoowweenn/qhack2022_proj)

### Resource Estimate: 

*A 1-2 paragraph written Resource Estimate, indicating how you expect to use the IBM 16-qubit QPU, if awarded, to finish your Open Hackathon project.*

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
