### ISSUE TITLE
[AWS Power Up] Quantum Computing -based Optimization for Sustainable Data Workflows in Cloud Infrastructures

### ISSUE THREAD

**Issue by valterUo** [XanaduAI/QHack2022#60]
### Team Name: 

Qumpula Quantum

### Project Description: 

Data centers are consuming a huge amount of energy and producing an unbearable carbon footprint. This work proposes a data workflow optimization algorithm that divides the data workload among multiple data centers so that the computations can be performed as sustainably as possible.

Google has developed a carbon footprint metric that enables users to track their computation emissions in their cloud infrastructure. Inspired by the idea that in the future such detailed data would be available, the project proposes a solution how to divide the computations along with data centers (or even machines in the centers) so that the carbon footprint is minimized. 

The problem is formulated as the shortest path finding problem in a weighted graph. Weights describe the carbon footprint of various workloads submitted to given data centers. Since emission data is not easily available, the situation is simulated and randomized for demonstration purposes. The work will implement a time component that takes into account that the sustainability of energy varies over time. 

The main goal of the project is to introduce quantum computing to the database community, raise awareness of climate change in the computer science community and learn to formulate QUBOs and solve them with various hardware and software.

Please find more details about sustainability in data centers and the theoretical background of the project in the paper draft with references in Github repo [Quantum Computing -based Optimization for Sustainable Data Workflows in Cloud Infrastructures](https://github.com/valterUo/Quantum-Computing-based-Optimization-for-Sustainable-Data-Workflows-in-Cloud/blob/main/Quantum_Computing__based_Optimization_for_Sustainable_Data_Workflows_in_Cloud.pdf).

Thanks for being part of organizing QHack!

### Source code: 

The main implementation can be accessed in [this Jupyter notebook](https://github.com/valterUo/Quantum-Computing-based-Optimization-for-Sustainable-Data-Workflows-in-Cloud/blob/main/main.ipynb).

### Resource Estimate: 

Currently, the project implements the version which connects to quantum annealers but I am very interested in learning to transform the problem into gate-based quantum computers. Currently, the data set size is small but I would like to scale up to see the performance differences between different quantum computers (annealers and NISQ) and classical computing. Besides this project, I have other database optimization ideas that I would implement on quantum computers.

![photo_2022-02-21_15-28-46](https://user-images.githubusercontent.com/33791450/155336919-dc1e9b77-d3b1-49da-893d-d992280d37bf.jpg)

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
