### ISSUE TITLE
[AWS Power Up] Quantum Music

### ISSUE THREAD

**Issue by toshi-koike-akino** [XanaduAI/QHack2022#63]
### Team Name: 

talll

### Project Description: 

Use quantum circuit to play piano and guitar. Given melody line, generate harmony chords etc. See [README.md](https://github.com/toshi-koike-akino/qusic/blob/main/README.md)

### Source code: 

A hyperlink to the draft source code for our team's hackathon project is found in [GitHub](https://github.com/toshi-koike-akino/qusic).

### Resource Estimate: 

More qubits can generate more variant of harmony chords.

### Open Hackathon Challenges/Prizes:

Our project is qualified for prizes:
- Amazon Braket Challenge
- IBM Qiskit Challenge
- and others

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
