### ISSUE TITLE
[AWS Power Up] Galaxy detection by QML

### ISSUE THREAD

**Issue by BrightSky77** [XanaduAI/QHack2022#66]
## 1. **Team Name**
   **Voyager**

## 2. **Project Description** 
This project is a further study of Saesun Kim's research on applying QML in image classification (https://github.com/bagmk/Quantum_Machine_Learning_Express)
This project is about applying qunatum machine learning in the field of astronomy. We are going to try to detect galaxy by image training in quantum circuit. We will divide the certain galaxy image into pixcels and use each pixcel as an input data. We will use quantum circuit from the paper [Expressibility and entangling capability of parameterized quantum circuits for hybrid quantum-classical algorithms, arXiv:1905. 10876] (https://arxiv.org/abs/1905.10876) and select the one that has high expressibility. Expressibility quantifies how circuit can express freely in Hilbert Space. We will use this quantum circuit for data embedding and QML model training, 

## 3. Source Code 
https://github.com/BrightSky77/Qhack_Quantum_Machine_Learning

## 4. Resource Estimate: 
By having access to AWS credits, we will be able to use more qubits so that we can process bigger size images.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
