### ISSUE TITLE
[AWS Power Up] Learning based error mitigation for VQE

### ISSUE THREAD

**Issue by Eyuel-E** [XanaduAI/QHack2022#67]
Team Name: edelweiss

@jeungrac @jyryu98 @Eyuel-E

Project Description:

Variational Quantum Eigensolvers (VQE) for calculating ground state energies of molecules are one of the major applications of noisy intermediate scale quantum (NISQ) computers. However for VQE to be viable on NISQ computers, powerful error mitigation protocols are needed due to the high level of noise.

In this project, we investigate applications of a learning based quantum error mitigation (LBEM) method [[1]](https://doi.org/10.1103/PRXQuantum.2.040330) on VQE for molecular ground state energy calculation. LBEM models an error free result with a quasi probabilistic mixture of noisy results. This distribution is learned via an ab initio process, without prior knowledge on the hardware error model. Clifford circuits are used for the training, so classical simulation is efficient, and the mitigation takes account of both spatial and temporal correlations.

[[1] Strikis, Armands, et al. "Learning-based quantum error mitigation." PRX Quantum 2.4 (2021): 040330.](https://doi.org/10.1103/PRXQuantum.2.040330)

Source code:

[Github repository](https://github.com/jyryu98/LBEM_for_VQE)

Resource Estimate:

We would like to use the AWS power up to access the quantum hardware provided by IonQ and Rigetti. We have implemented a method to mitigate hardware error.  So we would like to test its performance on different quantum architecture. Additional AWS credit would help us obtain the needed training set.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
