### ISSUE TITLE
[AWS Power Up] Your Project Title

### ISSUE THREAD

**Issue by ShivaneDadi05** [XanaduAI/QHack2022#69]
### Team Name: 

Quionizers

### Project Description: 

Computes the ground state binding energies of glutamine in order to facilitate speedups in the development of novel Covid-19 vaccines. A protease is an enzyme that works as a 'hammer', breaking down proteins into smaller amino acids and polypeptides. These amino acids and polypeptides then form long chains, allowing the virus to spread within its host. Covid-19 contains a protease called glutamine. By blocking the protease's receptors, we effectively halt the virus' ability to spread within its host. This can be done by reacting a protease inhibitor with the protease in order to stop the chemical process from occurring.

Current quantum hardware is not powerful enough to simulate whole macromolecules. However, as quantum computers get more and more powerful, so too will the ability to simulate molecular interactions. For this project, we simplified the glutamine molecule to create a so-called toy protease, in order to prove the effectiveness of quantum computers. By computing the bonding energy for the ground state toy protease, we can develop more sophisticated inhibitors that may be more effective against Covid variants

### Source code: 

https://github.com/Agurk2/qhack2022

### Resource Estimate: 

The project is dependent on the simulation of molecular interactions in the glutamine molecule. With access to AWS credits, we would have access to a quantum computing machine that is capable enough to simulate our protease model and also develop more sophisticated algorithms that can give greater accuracy in our simulation using optimization processes. Furthermore, with access to larger and more sophisticated quantum devices, we would be able to simulate larger models that can closely resemble the true glutamine molecule and facilitate speed-ups in the development of new SARS-Cov-2 vaccines, as current vaccines are losing evermore potency.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
