### ISSUE TITLE
[AWS Power Up] Deep quantum convolutional network

### ISSUE THREAD

**Issue by zuxfoucault** [XanaduAI/QHack2022#7]
### Team Name: 

*Your team's name (matching the name used on the QHack Coding Challenges, if applicable)* 
Quan

### Project Description: 

*A brief description of your project (1-2 paragraphs).*
Developing a quantum convolutional network with a skip connection network block.
 
### Source code: 

*A hyperlink to the draft source code for your team's hackathon project (e.g., a GitHub repo).*

### Resource Estimate: 

*A 1-2 paragraph written Resource Estimate, indicating how you expect to use the additional AWS credits, if awarded, to finish your Open Hackathon project.*
Mostly used in running Amazon Braket.

**Comment by co9olguy** [comment]
Thanks @zuxfoucault!

The deadline for this Power Up isn't until Wednesday next week, so feel free to update your project/submission (e.g., by adding a link to your draft code) before then :slightly_smiling_face:

**Comment by emkessler** [comment]
And feel free to swing by the amazon-braket-support slack channel if you have any questions regarding AWS or Braket. Happy building!

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
