### ISSUE TITLE
[AWS Power Up] Classical Neural Network assisted Variational Quantum Eigensolver and its Applications

### ISSUE THREAD

**Issue by Siddharthgolecha** [XanaduAI/QHack2022#70]
### Team Name: 

Qillers

### Project Description: 

Variational Quantum Eigensolver(VQE) is one of the most promising variational quantum/classical hybrid algorithms that efficiently find the minimum eigenvalue of a Hermitian matrix using near-term quantum computers. It is usually used in Quantum Chemistry to find the ground state energy of a simulated molecule. However, despite its success and promise as an algorithm to run over NISQ era quantum computers, it still faces some major challenges. One such challenge is to initialize good parameter heuristics that ensure rapid and consistent convergence to local minima of the parameterized quantum circuit landscape. This project uses the concept of the meta-learning(Classical Neural Network assisted VQEs), defined in this referenced paper[1], to rapidly find approximate optima in the parameter landscape. We train classical recurrent neural networks to find approximately optimal parameters within a small number of queries of the cost function for the VQE to demonstrate a significant improvement in the total number of optimization iterations required to reach a given accuracy. This project also aims to demonstrate various applications of the meta-learned VQE in Quantum Chemistry, Quantum Finance, and High Energy Physics and its potential speedup and performance improvement as compared to regular VQEs.

[1] Verdon, Guillaume, Mick Broughton, Jarrod R. McClean, Kevin J. Sung, Ryan Babbush, Zhang Jiang, Hartmut Neven and Masoud Mohseni. “Learning to learn with quantum neural networks via classical neural networks.” ArXiv abs/1907.05415 (2019): n. pag.

### Source code: 

https://github.com/Siddharthgolecha/Qillers

### Resource Estimate: 

I expect to use the AWS credits with AWS Bracket, if awarded, to design the VQEs at their full potential by simulating larger molecules in Quantum Chemistry, and a more constrained and larger portfolio optimization in Quantum Finance. The QPU would also be beneficial in calculating the more precise ground state energy value of HEP particles.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
