### ISSUE TITLE
[AWS Power Up] Your Project Title

### ISSUE THREAD

**Issue by mariandumitrascu** [XanaduAI/QHack2022#72]
### Team Name: 

Nobody
(but would like to change it to CognizantTeam)

### Project Description: 

I and my team would like to adapt Quirk visual interface to bracket. We would plan to build it using AWS platform, follow Amplify models. I am proficient in the full stack web ui and backend web technologies, certified AWS ML and SA (and also IBM QC developer certified). And we are very very very enthusiastic and into quantum computing. We work at Cognizant: Marian Dumitrascu and Allister Wright.

### Source code: 

Not yet

### Resource Estimate: 

We would use the AWS credits to host the project and integrate with bracket.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
