### ISSUE TITLE
[AWS Power Up] Dynamic Bayesian Network Structure Learning with three approaches

### ISSUE THREAD

**Issue by ixime** [XanaduAI/QHack2022#74]
### Team Name: 

*Your team's name (matching the name used on the QHack Coding Challenges, if applicable)*
ixi
### Project Description: 

*A brief description of your project (1-2 paragraphs).*

I am interested in dynamic bayesian network structure learning whose main goal is to obtain P(G|D), that means obtaining a direct acyclic graph (DAG) given a dataset of consisiting of at least two events or moments in time. This solution can be apply to solve problems in different fields, like finance, biology and ecology to name a few. This kind of problem is super-exponential (O(n! 2^(n!/(2!(n-2)!)))) [1] due to a search over all DAGs possible. I reviewed different approaches, and I decided to implement three different approaches:

1) Hybrid network = (classic) encoder + (quantum) circuit.
2) Variational circuit
3) Quantum circuit structure learning

The first step is to implement these approaches with a tiny dummy dataset of 4 variables (8 nodes) and if I get the AWS credits, implement them with a real dataset of microarray studies on cell cycle regulated genes. 

References: 
[1] Prashant S. Emani1, et al, Quantum Computing at the Frontiers of Biological Sciences

### Source code: 

*A hyperlink to the draft source code for your team's hackathon project (e.g., a GitHub repo).*
https://github.com/ixime/qhack_2022
### Resource Estimate: 

*A 1-2 paragraph written Resource Estimate, indicating how you expect to use the additional AWS credits, if awarded, to finish your Open Hackathon project.*
I would want to try out these approaches for real data of networks with more nodes, that means more qubits. I would want to try out simulations but also on real quantum computers.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
