### ISSUE TITLE
[AWS Power Up] Crypto Forecasting with Quantum Machine Learning

### ISSUE THREAD

**Issue by emilyfane** [XanaduAI/QHack2022#75]
### Team Name: 
CatsInHilbertSpace

### Project Description: 

Cryptocurrencies are notoriously volatile and challenging to predict, however, there is a great financial incentive in predicting their value. The purpose of this project is to compare quantum and classical machine learning methods for time series forecasting of cryptocurrency. In particular, this project analyzes the value of Ethereum, between 2015 and 2021 [Kaggle Ethereum Data - Arpit Verma](https://www.kaggle.com/varpit94/ethereum-data). There is a base model (model.py) used for loading and preprocessing data, and writing and plotting results, and the specific machine learning models (conv_model.py, q_seq_model.py) inherit from this model and implement functions for training and testing data. Currently, CNN, CNN with a quantum layer, and a self-designed variational quantum model are in progress, all using PennyLane and Torch, and if time permits, QRNN and LSTM will be implemented as well. 

### Source code: 

https://github.com/emilystamm/crypto_time_series_quantum

### Resource Estimate: 

The models use 6 logical qubits, and could run on IonQ, Rigetti, or simulators.  For IonQ, the cost estimate is as follows:
batch_size = 25
epochs = 10
test_size = 50
num_tries = 5
num_shots = 100

train_cost = (epochs * batch_size) * (.3 + .01 * num_shots)
test_cost = test_size * (.3 + .01 * num_shots)
total_cost = num_tries * (train_cost + test_cost)

total_cost = 1950.0.

**Comment by isaacdevlugt** [comment]
Thank you for your Power Up submission! As a reminder, the final deadline for your project is February 25 at 17h00 EST. Submissions should be done here: https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=&template=open_hackathon.md&title=%5BENTRY%5D+Your+Project+Title

This issue will be closed shortly.

Good luck!
