### ISSUE TITLE
[AWS Power Up]Image segmentation by QML and Grover algorithm. 

### ISSUE THREAD

**Issue by BrightSky77** [XanaduAI/QHack2022#9]
## 1. **Team Name**
   **Voyager**

## 2. **Project Description** 
This project is a further study of Saesun Kim's research on applying QML in image classification (https://github.com/bagmk/Quantum_Machine_Learning_Express)
We are going to detect the animal in infrared camera and the car object  in night camera by using QML and Grover algorithm.
After that , we are planning to compare the accuracy of detecting objects between those 2 methods.
Our goal is to apply QML and Grover algorithm, which was usually dealt only in theory, in practical fields like image segmentation and find the optimal method.    

## 3. Source Code 
https://github.com/BrightSky77/Qhack_Quantum_Machine_Learning

## 4. Resource Estimate: 
By having access to AWS credits, we will be able to use more qubits so that we can process more big size images.

**Comment by BrightSky77** [comment]
We already have team so we won't accept new members.

**Comment by co9olguy** [comment]
Thanks @BrightSky77 !

The deadline for Power Ups isn't until Wednesday, and final submissions isn't until Friday, so feel free to update your project/submission as you like before these deadlines

**Comment by BrightSky77** [comment]
Hello @co9olguy 
What do you mean by Power Ups? 
And does my team has to leave comments to be assigned to this project?

**Comment by isaacdevlugt** [comment]
Hey @BrightSky77, all information regarding Power Ups can be found here: https://github.com/XanaduAI/QHack#power-ups

**Comment by isaacdevlugt** [comment]
Please make sure to specify which power up you are applying for by labelling this issue. If you want to apply for both, please make a separate submission with the appropriate tag.

**Comment by BrightSky77** [comment]
Hello @isaacdevlugt 
I made an new issue for power up. It's an issue #66. How do I delete this issue #9?
